Repository MartinEGonzalez95/COOP, pull requests merged in 2019-10, with the labels that each got.

#16 Se integro COOP al COOPBrowser
  Cuis-University-COOP.pck.st
Labels: enhancement, usability

#17 Se elimino el popup al correr coop cuando se guarda un metodo
  Cuis-University-COOP.pck.st
Labels: enhancement

#18 Al Solucionarse una Regla es Borrada de la Vista COOP
  Cuis-University-COOP.pck.st
Labels: enhancement, usability

#20 Agrega Icono del Proyecto
  Icon.jpeg
  README.md
Labels: documentation

#19 COOP detecta una posible mejora cuando hay una cadena muy larga de colaboraciones
  Cuis-University-COOP.pck.st
Labels: enhancement

#21 COOP Hace Chequeo al Abrir un Metodo y al Aceptarlo
  Cuis-University-COOP.pck.st
Labels: enhancement, refactor

#22 Mejora sobre el recorrido del AST de nodos de las reglas
  Cuis-University-COOP.pck.st
Labels: enhancement, refactor

#23 COOP esta desacoplado del Text Editor
  Cuis-University-COOP.pck.st
Labels: refactor

#24 Arregla el Readme para que Tenga Mejor Legibilidad
  README.md
Labels: documentation

#25 COOP Prendido al Instalar Paquete y en Menu Principal
  Cuis-University-COOP.pck.st
Labels: enhancement, refactor

#26 COOP Detecta Miedo al Booleano
  Cuis-University-COOP.pck.st
Labels: enhancement

#27 COOP detecta una posible mejora cuando existe un test sin assert.
  Cuis-University-COOP.pck.st
Labels: enhancement

#28 Una regla me indica sobre que linea esta haciendo la sugerencia
  Cuis-University-COOP.pck.st
Labels: enhancement, usability
