Repository MartinEGonzalez95/COOP, pull requests merged in 2019-11, with the labels that each got.

#29 Agrega Documentación para 3er Entrega
  README.md
Labels: documentation

#30 COOP se vuelve a ejecutar cuando se crea un nuevo método o se deselecciona el actual.
  Cuis-University-COOP.pck.st
Labels: refactor, usability

#31 COOP Solo Resalta una Regla a la Vez
  Cuis-University-COOP.pck.st
Labels: enhancement, refactor

#32 Regla Miedo Al Booleano Puede Inspeccionar Clausulas sin Bloques
  Cuis-University-COOP.pck.st
Labels: bug

#33 Regla que chequea que los metodos de instancia no se envien a clase
  Cuis-University-COOP.pck.st
Labels: enhancement

#34 QuickFix para la regla CollectionSize
  Cuis-University-COOP.pck.st
Labels: enhancement, usability

#35 Agrega regla que detecta si se inicializa una variable con nil
  Cuis-University-COOP.pck.st
Labels: enhancement

#36 Agrega regla que chequea cuando se devuelve nil
  Cuis-University-COOP.pck.st
Labels: enhancement

#37 Agrega regla que valida cuando se envia nil como argumento
  Cuis-University-COOP.pck.st
Labels: enhancement

#38 Fix - Regla de mensaje de instancia
  Cuis-University-COOP.pck.st
Labels: bug, refactor
