Repository MartinEGonzalez95/COOP, pull requests merged in 2019-09, with the labels that each got.

#1 COOPHelper Crea Method Nodes
  Cuis-University-COOP-Tests.st
Labels: enhancement

#3 COOP detecta los mensajes a una Collection.
  Cuis-University-COOP-Tests.st
  Cuis-University-COOP.st
Labels: enhancement

#2 COOP Realiza Chequeo Interactivo Cuando el Parser Guarda un Metodo
  Cuis-University-COOP.st
  Parser-*Cuis-University-COOP.st
  Parser-performInteractiveChecks.st
Labels: enhancement

#4 COOP Detecta #isEmpty
  Cuis-University-COOP-Tests.st
  Cuis-University-COOP.st
  LeafNode-*Cuis-University-COOP.st
  ParseNode-*Cuis-University-COOP.st
  SelectorNode-*Cuis-University-COOP.st
Labels: enhancement

#5 COOP muestra un PopUp comentando una mejora
  Cuis-University-COOP-Tests.st
  Cuis-University-COOP.st
  Parser-*Cuis-University-COOP.st
  Parser-performInteractiveChecks.st
Labels: enhancement

#6 Cambios en el Readme
  .gitignore
  README.md
Labels: documentation

#7 Cambiar Files por Package
  Cuis-University-COOP.pck.st
  Cuis-University-COOP.st
  LeafNode-*Cuis-University-COOP.st
  ParseNode-*Cuis-University-COOP.st
  Parser-*Cuis-University-COOP.st
  SelectorNode-*Cuis-University-COOP.st
Labels: refactor

#8 Desacoplar RefactoringTest
  Cuis-University-COOP.pck.st
Labels: refactor

#10 Agrega el link del listado de reglas al README
  README.md
Labels: documentation

#9 [SPIKE] Ventana en el browser dentro de la vista del metodo
  Cuis-University-COOP.pck.st
Labels: enhancement, usability

#14 Refactor Feature Envy en COOP Window sobre Issue #12
  Cuis-University-COOP.pck.st
Labels: refactor

#11 Extrae el Source Code de los Test a Metodos Reales
  Cuis-University-COOP.pck.st
Labels: refactor

#15 Se muestran textos en el browser sobre las reglas
  Cuis-University-COOP.pck.st
Labels: enhancement
